eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka
    instance:
        preferIpAddress: true
server:
    port: 8082
spring:
    application:
      name: microService2
    datasource:
        driver-class-name: org.postgresql.Driver
        password: admin
        url: jdbc:postgresql://dbpostgresql2:5433/postgres
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
    rabbitmq:
        host: rabbitmq
        password: guest
        port: 15672
        username: guest
        exchange: user.exchange
        queue: user.queue
        queue2: user.queue2
        routingkey: user.routingkey
        routingkey2: user.routingkey2
