version: '3.8'

services:
  rabbitmq3:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - rabbitmq
  eureka-server:
    build: .\eurekaServer
    container_name: eureka-server
    expose:
      - 8761
  api-gateway:
    build: .\apiGateway
    container_name: api-gateway
    expose:
      - 8080
    depends_on:
      - eureka-server
  ui:
    build: .\Diyamonds_frontend
    container_name: diyamonds_frontend
    ports:
      - "4200:80"
    networks:
      - appbootrestnet
networks:
  rabbitmq:
    driver: bridge
  appbootrestnet:
    driver: bridge
# docker-compose build && docker-compose up

