version: '3'

services:
  dbpostgresql:
    container_name: postgres
    image: "postgres"
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appbootrestnet
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
  app:
    build: .\Diyamonds_backend
    image: appbootrest
    container_name: diyamonds_backend
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    networks:
      - appbootrestnet
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/postgres
     - SPRING_DATASOURCE_USERNAME=admin
     - SPRING_DATASOURCE_PASSWORD=admin
     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  ui:
    build: .\Diyamonds_frontend
    container_name: diyamonds_frontend
    ports:
      - "4200:80"
    networks:
      - appbootrestnet
    depends_on:
      - app

volumes:
  db-data:
  pgadmin-data:
networks:
  appbootrestnet:
    driver: bridge
# docker-compose build && docker-compose up

